package com.subhajit.SpringBootJPA.Controller;

import com.subhajit.SpringBootJPA.Service.EmployeeService;
import com.subhajit.SpringBootJPA.oracle1.entity.EmployeeEntity;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
public class EmployeeJpaController {
    @Autowired
    private EmployeeService employeeService;

    //pass an inputs in JSON format under body in Postman and store/add in Table/Pojo of EmployeeEntity

    /**
     * This is the sample JSON to be passed in postman.empId is autogenerated so no need to pass
     * {
     * "empCity" : "Panipat",
     * "empDept" : "IT",
     * "empName" : "Anil",
     * "empState" : "Haryana"
     * }
     * @param employeeEntity
     * @return
     */

    @PostMapping("/addEmployee")
    public ResponseEntity<Void> addEmployee(@RequestBody EmployeeEntity employeeEntity) {
        System.out.println("Employee added: " + employeeEntity);
        return employeeService.addEmployee(employeeEntity);                      //  return new ResponseEntity<>(employeeEntity, HttpStatus.CREATED);
    }

   // QAK: why manual entry added in table is not getting fetched; need commit on DB first
    @GetMapping("/fetchEmployeeRecords")
    public ResponseEntity<List<EmployeeEntity>> fetchAllEmployeeRecords() {
        //return new ResponseEntity(employeeService.fetchAllEmployeeRecords(), HttpStatus.OK);
        return employeeService.fetchAllEmployeeRecords(); //return like this
    }

    @GetMapping("fetchAnEmployeeRecord/{empId}")
    public ResponseEntity<EmployeeEntity> fetchAnEmployeeRecord(@PathVariable("empId") Long empId) {
        return employeeService.fetchAnEmployeeRecord(empId);
    }


    @DeleteMapping("/deleteAnEmployeeById/{empId}")
    public ResponseEntity<Void> deleteAnEmployeeById(@PathVariable("empId") Long empId) {
        return employeeService.deleteAnEmployeeById(empId);
        
    }

    @PutMapping("/updateAnEmployeeById/{empId}")
    public ResponseEntity<Void> updateAnEmployeeById(@PathVariable Long empId, @RequestBody EmployeeEntity employeeEntity) {
        return employeeService.updateAnEmployeeById(empId, employeeEntity);
    }
}
